### ISSUE TITLE
GB26875校验出错

### ISSUE THREAD

**Issue by bald-head** [chenqi92/allbs-model#2]
cn.allbs.utils.gb26875.format.GB26875Parser#readCheck
使用正确的指令会    报文数据校验不通过！
使用您博客提供的数据也会有问题
版本0.8.1

**Comment by chenqi92** [comment]
> cn.allbs.utils.gb26875.format.GB26875Parser#readCheck 使用正确的指令会 报文数据校验不通过！ 使用您博客提供的数据也会有问题 版本0.8.1

之前没写完而且还有bug😂已经修复了，明天发个版本
