### ISSUE TITLE
上传建筑消防设施部件运行状态 报警位不正确

### ISSUE THREAD

**Issue by fdj0926** [chenqi92/allbs-model#3]
消防主机报警后，通过gb26875Mapper解析出来的为 无火警

通过解析后发现 建筑消防设施系统状态 中的 系统状态 的2字节分别为 2,0
由于低字节传输在前，所以解析为16位二进制为 0000 0000 0000 0010 对应为有火警
![image](https://github.com/user-attachments/assets/977429dc-c207-4409-9fd9-0109eb2f6dcd)

在代码中打断点后定位到这里
![image](https://github.com/user-attachments/assets/ffbc1301-6e91-41e9-b206-735daae19594)
这里解析出来的sb变量为0000 0010 0000 0000，高低位颠倒了导致解析不正确
于是找到bs的上一方法，将赋值操作翻转，再次解析后报文正确
![image](https://github.com/user-attachments/assets/0168c1c8-bc20-4df9-8862-56ab0b23831a)

**Comment by chenqi92** [comment]
感谢指正，已修改
